/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author rebek
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblnome = new javax.swing.JLabel();
        lblcargo = new javax.swing.JLabel();
        lblGAcesso = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel7 = new javax.swing.JLabel();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        jLabel12 = new javax.swing.JLabel();
        telaFundo = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        hospedes = new javax.swing.JMenu();
        menuCadHospede = new javax.swing.JMenuItem();
        menuConHospede = new javax.swing.JMenuItem();
        quartos = new javax.swing.JMenu();
        menuCadQuartos = new javax.swing.JMenuItem();
        menuConQuartos = new javax.swing.JMenuItem();
        funcionarios = new javax.swing.JMenu();
        menuCadFuncionarios = new javax.swing.JMenuItem();
        menuConFuncionarios = new javax.swing.JMenuItem();
        fornecedores = new javax.swing.JMenu();
        menuCadFornecedores = new javax.swing.JMenuItem();
        menuConFornecedores = new javax.swing.JMenuItem();
        produtos = new javax.swing.JMenu();
        menuCadProdutos = new javax.swing.JMenuItem();
        menuConProdutos = new javax.swing.JMenuItem();
        serviços = new javax.swing.JMenu();
        menuCadServiços = new javax.swing.JMenuItem();
        menuConServiços = new javax.swing.JMenuItem();
        menuReservas = new javax.swing.JMenu();
        cadastrarReserva = new javax.swing.JMenu();
        consultarReserva = new javax.swing.JMenu();
        menuVendas = new javax.swing.JMenu();
        produtoVendas = new javax.swing.JMenu();
        serviçoVendas = new javax.swing.JMenu();
        menuFinanceiro = new javax.swing.JMenu();
        ContasAPagar = new javax.swing.JMenu();
        menuCadContPagar = new javax.swing.JMenuItem();
        menuConContPagar = new javax.swing.JMenuItem();
        ContasAReceber = new javax.swing.JMenu();
        menuCadContPaga = new javax.swing.JMenuItem();
        menuConContRec = new javax.swing.JMenuItem();
        Balanço = new javax.swing.JMenu();
        menuFerramentas = new javax.swing.JMenu();
        sobreOSistema = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(29, 45, 88));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 975, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pallace_hotel_icon_256x256.2.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(29, 45, 88));
        jLabel3.setText("PALLACE HOTEL");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("horário do sistema");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Usuário:");

        lblnome.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblnome.setText("nome");

        lblcargo.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblcargo.setText("texto");

        lblGAcesso.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblGAcesso.setText("texto");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Cargo:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("G. Acesso:");

        jCalendar1.setWeekOfYearVisible(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Check-in Hospedes");

        jCalendar2.setWeekOfYearVisible(false);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Check-out Hospedes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel3)))
                .addGap(0, 69, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcargo)
                                    .addComponent(lblnome)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblGAcesso))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(jCalendar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblnome, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGAcesso)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout telaFundoLayout = new javax.swing.GroupLayout(telaFundo);
        telaFundo.setLayout(telaFundoLayout);
        telaFundoLayout.setHorizontalGroup(
            telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        telaFundoLayout.setVerticalGroup(
            telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        menuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastro.png"))); // NOI18N
        menuCadastro.setText("Cadastros   |");

        hospedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_hospede.png"))); // NOI18N
        hospedes.setText("Hospedes");

        menuCadHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_cadrastar_20x20.png"))); // NOI18N
        menuCadHospede.setText("Cadastrar");
        menuCadHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospedeActionPerformed(evt);
            }
        });
        hospedes.add(menuCadHospede);

        menuConHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_consultar_20x20.png"))); // NOI18N
        menuConHospede.setText("Consultar");
        menuConHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConHospedeActionPerformed(evt);
            }
        });
        hospedes.add(menuConHospede);

        menuCadastro.add(hospedes);

        quartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_quarto.png"))); // NOI18N
        quartos.setText("Quartos");

        menuCadQuartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_quarto.png"))); // NOI18N
        menuCadQuartos.setText("Cadastrar");
        menuCadQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadQuartosActionPerformed(evt);
            }
        });
        quartos.add(menuCadQuartos);

        menuConQuartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconQuartoCon_20x20.png"))); // NOI18N
        menuConQuartos.setText("Consultar");
        menuConQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConQuartosActionPerformed(evt);
            }
        });
        quartos.add(menuConQuartos);

        menuCadastro.add(quartos);

        funcionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_funcionario.png"))); // NOI18N
        funcionarios.setText("Funcionários");

        menuCadFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_cadrastar_20x20.png"))); // NOI18N
        menuCadFuncionarios.setText("Cadastrar");
        menuCadFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFuncionariosActionPerformed(evt);
            }
        });
        funcionarios.add(menuCadFuncionarios);

        menuConFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_consultar_20x20.png"))); // NOI18N
        menuConFuncionarios.setText("Consultar");
        menuConFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConFuncionariosActionPerformed(evt);
            }
        });
        funcionarios.add(menuConFuncionarios);

        menuCadastro.add(funcionarios);

        fornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_fornecedor.png"))); // NOI18N
        fornecedores.setText("Fornecedores");

        menuCadFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_cadrastar_20x20.png"))); // NOI18N
        menuCadFornecedores.setText("Cadastrar");
        menuCadFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFornecedoresActionPerformed(evt);
            }
        });
        fornecedores.add(menuCadFornecedores);

        menuConFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_consultar_20x20.png"))); // NOI18N
        menuConFornecedores.setText("Consultar");
        menuConFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConFornecedoresActionPerformed(evt);
            }
        });
        fornecedores.add(menuConFornecedores);

        menuCadastro.add(fornecedores);

        produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_poroduto_20x20.png"))); // NOI18N
        produtos.setText("Produtos");

        menuCadProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_produtos.png"))); // NOI18N
        menuCadProdutos.setText("Cadastrar");
        menuCadProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadProdutosActionPerformed(evt);
            }
        });
        produtos.add(menuCadProdutos);

        menuConProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconQuartoCon_20x20.png"))); // NOI18N
        menuConProdutos.setText("Consultar");
        menuConProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConProdutosActionPerformed(evt);
            }
        });
        produtos.add(menuConProdutos);

        menuCadastro.add(produtos);

        serviços.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_servicos.png"))); // NOI18N
        serviços.setText("Serviços");

        menuCadServiços.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_serviços_con.png"))); // NOI18N
        menuCadServiços.setText("Cadastrar");
        menuCadServiços.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadServiçosActionPerformed(evt);
            }
        });
        serviços.add(menuCadServiços);

        menuConServiços.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconQuartoCon_20x20.png"))); // NOI18N
        menuConServiços.setText("Consultar");
        menuConServiços.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConServiçosActionPerformed(evt);
            }
        });
        serviços.add(menuConServiços);

        menuCadastro.add(serviços);

        jMenuBar1.add(menuCadastro);

        menuReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/reservas.png"))); // NOI18N
        menuReservas.setText("Reservas   |");

        cadastrarReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_cad_reserva_20x20.png"))); // NOI18N
        cadastrarReserva.setText("Cadastrar Reserva");
        menuReservas.add(cadastrarReserva);

        consultarReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calendar_icon_20x20.png"))); // NOI18N
        consultarReserva.setText("Consultar Reserva");
        menuReservas.add(consultarReserva);

        jMenuBar1.add(menuReservas);

        menuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consumo.png"))); // NOI18N
        menuVendas.setText("Vendas   |  ");

        produtoVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_produtos.png"))); // NOI18N
        produtoVendas.setText("Produtos");
        menuVendas.add(produtoVendas);

        serviçoVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_servicos.png"))); // NOI18N
        serviçoVendas.setText("Serviços");
        menuVendas.add(serviçoVendas);

        jMenuBar1.add(menuVendas);

        menuFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/financeiro.png"))); // NOI18N
        menuFinanceiro.setText("Financeiro   |");

        ContasAPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_conta_paga.png"))); // NOI18N
        ContasAPagar.setText("Contas a Pagar");

        menuCadContPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_cad_conta.png"))); // NOI18N
        menuCadContPagar.setText("Cadastrar");
        menuCadContPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadContPagarActionPerformed(evt);
            }
        });
        ContasAPagar.add(menuCadContPagar);

        menuConContPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_conta_consulta.png"))); // NOI18N
        menuConContPagar.setText("Consultar");
        ContasAPagar.add(menuConContPagar);

        menuFinanceiro.add(ContasAPagar);

        ContasAReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_conta_recebe.png"))); // NOI18N
        ContasAReceber.setText("Contas a Receber");

        menuCadContPaga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_cad_conta.png"))); // NOI18N
        menuCadContPaga.setText("Cadastrar");
        menuCadContPaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadContPagaActionPerformed(evt);
            }
        });
        ContasAReceber.add(menuCadContPaga);

        menuConContRec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_conta_consulta.png"))); // NOI18N
        menuConContRec.setText("Consultar");
        menuConContRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConContRecActionPerformed(evt);
            }
        });
        ContasAReceber.add(menuConContRec);

        menuFinanceiro.add(ContasAReceber);

        Balanço.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_balanco.png"))); // NOI18N
        Balanço.setText("Balanço");
        menuFinanceiro.add(Balanço);

        jMenuBar1.add(menuFinanceiro);

        menuFerramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ferramentas.png"))); // NOI18N
        menuFerramentas.setText("Ferramentas   |");

        sobreOSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_sistema.png"))); // NOI18N
        sobreOSistema.setText("Sobre o Sistema");
        menuFerramentas.add(sobreOSistema);

        jMenuBar1.add(menuFerramentas);

        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        menuSair.setText("Sair");
        menuSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(telaFundo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
                    .addComponent(telaFundo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospedeActionPerformed
        // TODO add your handling code here:
        TelaCadastroHospede hospede = new TelaCadastroHospede();
        telaFundo.add(hospede);
        hospede.setVisible(true);
    }//GEN-LAST:event_menuCadHospedeActionPerformed

    private void menuConFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConFuncionariosActionPerformed
        // TODO add your handling code here:
        TelaCadastroFuncionario consulta = new TelaCadastroFuncionario();
        telaFundo.add(consulta);
        consulta.setVisible(true);
    }//GEN-LAST:event_menuConFuncionariosActionPerformed

    private void menuCadFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFornecedoresActionPerformed
        // TODO add your handling code here:
        TelaCadastroFornecedores fornecedor = new TelaCadastroFornecedores();
        telaFundo.add(fornecedor);
        fornecedor.setVisible(true);
    }//GEN-LAST:event_menuCadFornecedoresActionPerformed

    private void menuCadContPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadContPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadContPagarActionPerformed

    private void menuCadContPagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadContPagaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadContPagaActionPerformed

    private void menuConContRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConContRecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuConContRecActionPerformed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSairMouseClicked

    private void menuCadFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFuncionariosActionPerformed
        // TODO add your handling code here:
        TelaCadastroFuncionario cadastro = new TelaCadastroFuncionario();
        telaFundo.add(cadastro);
        cadastro.setVisible(true);
    }//GEN-LAST:event_menuCadFuncionariosActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        // TODO add your handling code here:
        TelaLogin sair = new TelaLogin();
        this.dispose();
        sair.setVisible(true);

        
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuCadQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadQuartosActionPerformed
        // TODO add your handling code here:
        TelaCadastroQuartos quarto = new TelaCadastroQuartos();
        telaFundo.add(quarto);
        quarto.setVisible(true);
    }//GEN-LAST:event_menuCadQuartosActionPerformed

    private void menuCadProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadProdutosActionPerformed
        // TODO add your handling code here:
        TelaCadastroProduto produto = new TelaCadastroProduto();
        telaFundo.add(produto);
        produto.setVisible(true);
    }//GEN-LAST:event_menuCadProdutosActionPerformed

    private void menuCadServiçosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadServiçosActionPerformed
        // TODO add your handling code here:
        TelaCadastroServiços servico = new TelaCadastroServiços();
        telaFundo.add(servico);
        servico.setVisible(true);
    }//GEN-LAST:event_menuCadServiçosActionPerformed

    private void menuConHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConHospedeActionPerformed
        // TODO add your handling code here:
        TelaConsultaPadrao consultaCad = new TelaConsultaPadrao();
        telaFundo.add(consultaCad);
        consultaCad.setVisible(true);
    }//GEN-LAST:event_menuConHospedeActionPerformed

    private void menuConQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConQuartosActionPerformed
        // TODO add your handling code here:
        TelaConsultaPadrao consultaCad = new TelaConsultaPadrao();
        telaFundo.add(consultaCad);
        consultaCad.setVisible(true);
    }//GEN-LAST:event_menuConQuartosActionPerformed

    private void menuConFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConFornecedoresActionPerformed
        // TODO add your handling code here:
        TelaConsultaPadrao consultaCad = new TelaConsultaPadrao();
        telaFundo.add(consultaCad);
        consultaCad.setVisible(true);
    }//GEN-LAST:event_menuConFornecedoresActionPerformed

    private void menuConProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConProdutosActionPerformed
        // TODO add your handling code here:
        TelaConsultaPadrao consultaCad = new TelaConsultaPadrao();
        telaFundo.add(consultaCad);
        consultaCad.setVisible(true);
    }//GEN-LAST:event_menuConProdutosActionPerformed

    private void menuConServiçosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConServiçosActionPerformed
        // TODO add your handling code here:
        TelaConsultaPadrao consultaCad = new TelaConsultaPadrao();
        telaFundo.add(consultaCad);
        consultaCad.setVisible(true);
    }//GEN-LAST:event_menuConServiçosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Balanço;
    private javax.swing.JMenu ContasAPagar;
    private javax.swing.JMenu ContasAReceber;
    private javax.swing.JMenu cadastrarReserva;
    private javax.swing.JMenu consultarReserva;
    private javax.swing.JMenu fornecedores;
    private javax.swing.JMenu funcionarios;
    private javax.swing.JMenu hospedes;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblGAcesso;
    private javax.swing.JLabel lblcargo;
    private javax.swing.JLabel lblnome;
    private javax.swing.JMenuItem menuCadContPaga;
    private javax.swing.JMenuItem menuCadContPagar;
    private javax.swing.JMenuItem menuCadFornecedores;
    private javax.swing.JMenuItem menuCadFuncionarios;
    private javax.swing.JMenuItem menuCadHospede;
    private javax.swing.JMenuItem menuCadProdutos;
    private javax.swing.JMenuItem menuCadQuartos;
    private javax.swing.JMenuItem menuCadServiços;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuConContPagar;
    private javax.swing.JMenuItem menuConContRec;
    private javax.swing.JMenuItem menuConFornecedores;
    private javax.swing.JMenuItem menuConFuncionarios;
    private javax.swing.JMenuItem menuConHospede;
    private javax.swing.JMenuItem menuConProdutos;
    private javax.swing.JMenuItem menuConQuartos;
    private javax.swing.JMenuItem menuConServiços;
    private javax.swing.JMenu menuFerramentas;
    private javax.swing.JMenu menuFinanceiro;
    private javax.swing.JMenu menuReservas;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuVendas;
    private javax.swing.JMenu produtoVendas;
    private javax.swing.JMenu produtos;
    private javax.swing.JMenu quartos;
    private javax.swing.JMenu serviçoVendas;
    private javax.swing.JMenu serviços;
    private javax.swing.JMenu sobreOSistema;
    private javax.swing.JDesktopPane telaFundo;
    // End of variables declaration//GEN-END:variables
}
